server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: college-platform-backend
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/college_platform?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 0

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: assign_id
      logic-delete-field: isDeleted
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

jwt:
  secret: c2VjcmV0S2V5Rm9yQ29sbGVnZVBsYXRmb3JtQXBwbGljYXRpb25TZWN1cml0eQ== # 随机配置的 Base64 密钥
  expiration: 86400000 # TOKEN 默认 24小时有效
